const API_URL = "https://script.google.com/macros/s/AKfycbyqd9R3oJKeM5RBBW52MAhobmQCJVmOkF2fA69nPwTG2C48yc5F0s7XQ8wJJZpksRV4cA/exec";
let appData={onProcess:[],stock:[],upload:[],boosterLive:[]},currentPage="home",searchTerm="";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
window.addEventListener("DOMContentLoaded",init);
async function init(){bindNav();bindSearch();bindFab();injectStyles();await loadData();}
async function loadData(){showLoading(true);try{const r=await fetch(API_URL+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const raw=await r.json(),d=raw?.data||raw;appData={onProcess:arr(d,["onProcess","onprocess"]),stock:arr(d,["stock"]),upload:arr(d,["upload"]),boosterLive:arr(d,["boosterLive","boosterlive","booster"])};renderPage(currentPage);}catch(e){console.error(e);renderError("Gagal mengambil data Google Sheets.");showToast("Gagal mengambil data");}finally{showLoading(false);}}
function arr(d,keys){for(const k of keys)if(Array.isArray(d?.[k]))return d[k];return[];}
function bindNav(){$$('[data-page]').forEach(b=>b.addEventListener("click",()=>{currentPage=b.dataset.page||"home";setActive();renderPage(currentPage);window.scrollTo({top:0,behavior:"smooth"});}));}
function setActive(){$$('.menu-item,.bottom-item').forEach(b=>b.classList.toggle("active",b.dataset.page===currentPage));}
function bindSearch(){const i=$("#searchInput");if(i)i.addEventListener("input",e=>{searchTerm=e.target.value.toLowerCase().trim();renderPage(currentPage);});}
function bindFab(){const b=$("#fab");if(b)b.addEventListener("click",openAddModal);}
function renderPage(p){const t=$("#pageTitle"),g=$("#dashboardGrid"),c=$("#contentArea");if(!t||!g||!c)return;const names={home:"Dashboard",onprocess:"On Process",stock:"Stock Konten",upload:"Konten Terupload",booster:"Booster Live"};t.textContent=names[p]||"Dashboard";g.innerHTML="";c.innerHTML="";if(p==="home")return home();const d=p==="onprocess"?appData.onProcess:p==="stock"?appData.stock:p==="upload"?appData.upload:appData.boosterLive;section(d,p);}
function home(){const g=$("#dashboardGrid"),c=$("#contentArea");const stats=[["On Process",appData.onProcess.length,"fa-pen-to-square","onprocess"],["Stock",appData.stock.length,"fa-box","stock"],["Upload",appData.upload.length,"fa-film","upload"],["Booster Live",appData.boosterLive.length,"fa-rocket","booster"]];g.innerHTML=stats.map(x=>`<button class="card stat-card" data-page="${x[3]}" type="button"><div class="card-header"><h3>${x[0]}</h3><span><i class="fa-solid ${x[2]}"></i></span></div><div class="card-body"><strong class="stat-number">${x[1]}</strong></div></button>`).join("");g.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;setActive();renderPage(currentPage);});const latest=filter(appData.upload).slice(-6).reverse();c.innerHTML=`<div class="section-heading"><div><h2>Konten Terbaru</h2><p>${latest.length} konten terakhir</p></div></div><div class="card-grid">${latest.length?latest.map(uploadCard).join(""):empty("Belum ada data upload.")}</div>`;}
function section(data,type){const d=filter(data),c=$("#contentArea");c.innerHTML=`<div class="section-heading"><div><h2>${name(type)}</h2><p>${d.length} data</p></div></div><div class="card-grid">${d.length?d.map(x=>card(x,type)).join(""):empty(type==="onprocess"?"Data On Process belum diterima dari API Google Sheets.":"Tidak ada data yang ditemukan.")}</div>`;}
function card(x,t){if(t==="onprocess")return onCard(x);if(t==="stock")return stockCard(x);if(t==="upload")return uploadCard(x);return boosterCard(x);}
function onCard(x){return cardTpl(v(x,"judul","onprocess")||"Tanpa Judul",fields([["Editor","editor"],["Bahan mentah diterima","bahan"],["Mulai edit","mulaiEdit"],["Konten jadi","jadiKonten"],["Upload grup review","uploadReview"],["Tanggal ACC","acc"],["Status","status"],["Keterangan","keterangan"]],x,"onprocess"));}
function stockCard(x){return cardTpl(v(x,"judul","stock")||"Tanpa Judul",fields([["Akun TikTok","akun"],["Editor","editor"],["Selesai edit","selesaiEdit"],["Upload grup review","uploadReview"],["Tanggal ACC","acc"],["Penjadwalan","jadwal"],["Keterangan","keterangan"]],x,"stock")+link(v(x,"link","stock")));}
function uploadCard(x){const b=v(x,"jenisBooster","upload"),url=v(x,"link","upload");return cardTpl(v(x,"judul","upload")||"Tanpa Judul",fields([["Akun TikTok","akun"],["Editor","editor"],["Tanggal Upload TikTok","uploadTikTok"],["Tanggal ACC","acc"],["Jenis Booster","jenisBooster"],["Nominal Booster","nominalBooster"],["Asal Dana Booster","asalDana"]],x,"upload")+performance(x)+review(url));}
function boosterCard(x){return cardTpl(v(x,"cabang","booster")||"Booster Live",fields([["Tanggal Booster","tanggal"],["Asal biaya","asalBiaya"],["Budget","budget"],["Host Live","host"]],x,"booster"));}
function fields(list,x,s){return list.map(a=>`<p><b>${esc(a[0])}</b><br>${esc(v(x,a[1],s)||"-")}</p>`).join("");}
function cardTpl(t,b){return `<article class="card content-card"><div class="card-header"><h3>${esc(t)}</h3><span><i class="fa-solid fa-chart-simple"></i></span></div><div class="card-body">${b}</div></article>`;}
function performance(x){const a=v(x,"viewsBefore","upload"),b=v(x,"viewsAfter","upload"),c=v(x,"likesBefore","upload"),d=v(x,"likesAfter","upload");if(!a&&!b&&!c&&!d&&!v(x,"jenisBooster","upload"))return"";return `<div class="performance-box"><div class="performance-title"><i class="fa-solid fa-chart-line"></i> Performa Konten</div><div class="performance-grid"><div><span>Views Sebelum Booster</span><strong>${esc(a||"-")}</strong></div><div><span>Views Setelah Booster</span><strong>${esc(b||"-")}</strong></div><div><span>Likes Sebelum Booster</span><strong>${esc(c||"-")}</strong></div><div><span>Likes Setelah Booster</span><strong>${esc(d||"-")}</strong></div></div></div>`;}
function review(url){if(!/^https?:\/\//i.test(url||""))return"";return `<p><button type="button" class="preview-button" data-preview-url="${attr(url)}"><i class="fa-brands fa-tiktok"></i> Review Konten</button></p>`;}
function link(url){if(!/^https?:\/\//i.test(url||""))return"";return `<p><a href="${attr(url)}" target="_blank" rel="noopener noreferrer">Buka Konten <i class="fa-solid fa-arrow-up-right-from-square"></i></a></p>`;}
function filter(d){if(!searchTerm)return d||[];return(d||[]).filter(x=>Object.values(x||{}).some(y=>String(y??"").toLowerCase().includes(searchTerm)));}
function name(t){return{onprocess:"On Process",stock:"Stock Konten",upload:"Konten Terupload",booster:"Booster Live"}[t]||"Data";}
function empty(t){return `<div class="empty-state"><h3>${esc(t)}</h3></div>`;}
function renderError(t){const c=$("#contentArea");if(c)c.innerHTML=empty(t);}
function norm(k){return String(k??"").toLowerCase().replace(/[\u00a0\r\n]+/g," ").replace(/[^a-z0-9]+/g,"");}
function v(x,type,s){const A={judul:["judulkonten","judul","namakonten","title"],editor:["editor"],akun:["akuntiktok","akun"],bahan:["tanggalbahanmentahditerima","bahanmentahditerima","tanggalbahan"],mulaiEdit:["tanggalmulaiedit","mulaiedit"],jadiKonten:["tanggaljadikonten","jadikonten"],uploadReview:["tanggaluploadkegrupreview","uploadkegrupreview","tanggaluploadreview"],acc:["tanggalacckonten","tanggalacc","acc"],status:["status"],keterangan:["keterangan","keterengan","catatan"],selesaiEdit:["tanggalselesaiedit","tanggalselesai"],jadwal:["penjadwalankontenupload","penjadwalan","jadwal"],link:["linkkonten","link","url"],uploadTikTok:["tanggaluploadtiktok","tanggalupload","uploadtiktok"],jenisBooster:["jenisbooster","booster"],nominalBooster:["nominalbooster"],asalDana:["asaldanabooster","asaldana"],viewsBefore:["viewsbefore","viewbefore","viewsebelum","jumlahviewlikesebelumbooster"],likesBefore:["likesbefore","likebefore","likessebelum","jumlahlikebefore"],viewsAfter:["viewsafter","viewafter","viewsetelah","jumlahviewlikesetelahbooster"],likesAfter:["likesafter","likeafter","likesetelah","jumlahviewlikesetelahbooster"],cabang:["cabangyangdibooster","cabang"],tanggal:["tanggalbooster","tanggal"],asalBiaya:["asalbiayabooster","asalbiaya"],budget:["budgetbooster","budget"],host:["hostlive","host"]};const wanted=(A[type]||[type]).map(norm);if(Array.isArray(x)){const M={onprocess:{judul:1,bahan:2,mulaiEdit:3,jadiKonten:4,editor:5,uploadReview:6,acc:7,status:8,keterangan:9},stock:{judul:1,selesaiEdit:2,uploadReview:3,acc:4,akun:5,editor:6,jadwal:7,keterangan:8,link:9},upload:{judul:1,selesaiEdit:2,uploadReview:3,acc:4,akun:5,uploadTikTok:6,editor:7,jenisBooster:8,nominalBooster:9,asalDana:10,viewsBefore:13,likesBefore:14,viewsAfter:15,likesAfter:16,link:17},booster:{cabang:1,tanggal:2,asalBiaya:3,budget:4,host:5}};return String(x[M[s]?.[type]]??"").trim();}if(!x||typeof x!=="object")return"";const entries=Object.entries(x);for(const[k,val]of entries)if(wanted.includes(norm(k)))return String(val??"").trim();const sem={viewsBefore:/view.*sebelum/i,viewsAfter:/view.*setelah/i,likesBefore:/like.*sebelum/i,likesAfter:/like.*setelah/i,judul:/judul|title|nama.*konten/i,akun:/akun.*tiktok/i,link:/link|url/i,uploadTikTok:/upload.*tiktok/i,jenisBooster:/jenis.*booster/i,nominalBooster:/nominal.*booster/i,asalDana:/asal.*dana/i,editor:/^editor$/i};if(sem[type])for(const[k,val]of entries)if(sem[type].test(k))return String(val??"").trim();return"";}
function esc(x){return String(x??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}function attr(x){return esc(x);}function showLoading(x){const e=$("#loading");if(e)e.classList.toggle("show",!!x);}function showToast(x){const e=$("#toast");if(!e)return;e.textContent=x;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500);}
function openAddModal(){let m=$("#addModal");if(!m){m=document.createElement("div");m.id="addModal";m.className="simple-modal";m.innerHTML=`<div class="simple-modal-box"><button class="simple-modal-close">×</button><h2>Tambah Konten</h2><p class="modal-note">Form input siap ditambahkan ke tahap berikutnya.</p><button class="modal-ok">Tutup</button></div>`;document.body.appendChild(m);m.querySelector(".simple-modal-close").onclick=()=>m.remove();m.querySelector(".modal-ok").onclick=()=>m.remove();}}
function injectStyles(){if($("#cbm-fixed-styles"))return;const s=document.createElement("style");s.id="cbm-fixed-styles";s.textContent=`.performance-box{margin:14px 0;padding:14px;border-radius:14px;background:#f6f8fc;border:1px solid #e8edf5}.performance-title{font-weight:800;margin-bottom:10px;color:#0f172a}.performance-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.performance-grid>div{background:#fff;border-radius:10px;padding:11px;border:1px solid #e8edf5}.performance-grid span{display:block!important;visibility:visible!important;opacity:1!important;font-size:11px!important;color:#64748b!important;font-weight:700!important;margin-bottom:5px!important;line-height:1.3!important}.performance-grid strong{display:block!important;color:#0f172a!important;font-size:16px!important}.simple-modal{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;background:rgba(10,18,35,.65);padding:20px}.simple-modal-box{background:#fff;border-radius:20px;padding:28px;width:min(420px,92vw)}.simple-modal-close{float:right;border:0;background:#eee;border-radius:50%;width:34px;height:34px;font-size:22px}.modal-ok{border:0;border-radius:10px;padding:10px 16px}`;document.head.appendChild(s);}
